import { UCL_CALENDAR, UCL_START } from "@/data/ucl";
import {
  EUROPEAN_START,
  europeanCalendar,
} from "@/data/europeanCompetitions";
import { NATIONAL_CUP_START } from "@/lib/calendarRules";
import { getCupStructureForCountry } from "@/lib/cups";
import type { Fixture } from "@/lib/season";
import { LEAGUES } from "@/data/teams";
import { addDaysToIso } from "@/lib/transferWindows";

function validIso(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const iso = value.slice(0, 10);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(iso)) return null;
  const time = Date.parse(`${iso}T12:00:00Z`);
  return Number.isFinite(time) ? iso : null;
}

function offsetToIso(start: string, offset: number): string {
  return addDaysToIso(start, offset);
}

export function getEuropeanFixtureDateIso(
  fixture: Pick<Fixture, "date" | "matchday" | "round" | "europeanCompetition" | "competition">,
  competitionHint?: "ucl" | "uel" | "uecl",
): string | null {
  // UEFA dates are part of the fixed competition calendar. Prefer the
  // canonical round date over any persisted `fixture.date`, because older
  // saves may contain a legacy +/-1 day value from the shared UCL engine.
  const stored = validIso(fixture.date);

  const comp = competitionHint ?? fixture.europeanCompetition ?? (fixture.competition === "ucl" ? "ucl" : undefined);
  if (!comp) return stored;

  const start = comp === "ucl" ? UCL_START : EUROPEAN_START;
  const calendar = comp === "ucl" ? UCL_CALENDAR : europeanCalendar();
  const round = String(fixture.round ?? "");
  const jornada = round.match(/^Jornada\s+(\d+)$/i);

  if (jornada) {
    const index = Number(jornada[1]) - 1;
    const offset = calendar.leagueDay[index];
    if (offset != null) return offsetToIso(start, offset);
  }

  const knockoutOffsets: Record<string, number | undefined> = {
    "Playoff-Leg1": calendar.playoffLeg1,
    "Playoff-Leg2": calendar.playoffLeg2,
    "R16-Leg1": calendar.r16Leg1,
    "R16-Leg2": calendar.r16Leg2,
    "QF-Leg1": calendar.qfLeg1,
    "QF-Leg2": calendar.qfLeg2,
    "SF-Leg1": calendar.sfLeg1,
    "SF-Leg2": calendar.sfLeg2,
    Final: calendar.final,
  };
  const offset = knockoutOffsets[round];
  if (offset != null) return offsetToIso(start, offset);

  const raw = Number(fixture.matchday);
  if (Number.isFinite(raw)) {
    const engineOffset = comp === "ucl" ? raw : raw - 1;
    if (engineOffset >= 0) {
      if (comp === "ucl") return offsetToIso(start, engineOffset);
      // Legacy UEL/UECL fixtures were generated by the Champions engine.
      // Recover the Thursday of that UEFA week instead of treating the engine
      // Tuesday/Wednesday offset as the actual Europa/Conference date.
      const base = new Date(`${start}T00:00:00Z`);
      const weekday = new Date(base.getTime() + engineOffset * 86400000).getUTCDay();
      const delta = (4 - weekday + 7) % 7 || 7;
      return offsetToIso(start, engineOffset + delta);
    }
  }

  // Unknown/custom round: keep a valid persisted date rather than inventing
  // a new one. Known UEFA rounds above always return their fixed date first.
  return stored;
}

export function getCupFixtureDateIso(
  fixture: Pick<Fixture, "date" | "matchday" | "round" | "league">,
): string | null {
  const stored = validIso(fixture.date);

  // National-cup dates are also fixed. Prefer the round's canonical schedule
  // over a legacy persisted date so old saves cannot silently move a cup tie.
  if (fixture.round && fixture.league) {
    try {
      const countryName = LEAGUES[fixture.league]?.country;
      if (countryName) {
        const step = getCupStructureForCountry(countryName).schedule.find(
          (item: any) => item.round === fixture.round,
        );
        if (step?.matchday != null) {
          return offsetToIso(NATIONAL_CUP_START, Number(step.matchday));
        }
      }
    } catch {
      // Keep compatibility with custom/legacy fixtures below.
    }
  }

  if (stored) return stored;
  const offset = Number(fixture.matchday);
  return Number.isFinite(offset) ? offsetToIso(NATIONAL_CUP_START, offset) : null;
}
