/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as SquadRouteImport } from './routes/squad'
import { Route as SeasonRouteImport } from './routes/season'
import { Route as ScorersRouteImport } from './routes/scorers'
import { Route as MatchRouteImport } from './routes/match'
import { Route as LineupRouteImport } from './routes/lineup'
import { Route as InjuriesRouteImport } from './routes/injuries'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as CupRouteImport } from './routes/cup'
import { Route as ChampionsRouteImport } from './routes/champions'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AssistsRouteImport } from './routes/assists'
import { Route as IndexRouteImport } from './routes/index'

const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadRoute = SquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonRoute = SeasonRouteImport.update({
  id: '/season',
  path: '/season',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorersRoute = ScorersRouteImport.update({
  id: '/scorers',
  path: '/scorers',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const LineupRoute = LineupRouteImport.update({
  id: '/lineup',
  path: '/lineup',
  getParentRoute: () => rootRouteImport,
} as any)
const InjuriesRoute = InjuriesRouteImport.update({
  id: '/injuries',
  path: '/injuries',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const CupRoute = CupRouteImport.update({
  id: '/cup',
  path: '/cup',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionsRoute = ChampionsRouteImport.update({
  id: '/champions',
  path: '/champions',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistsRoute = AssistsRouteImport.update({
  id: '/assists',
  path: '/assists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assists': typeof AssistsRoute
  '/calendar': typeof CalendarRoute
  '/champions': typeof ChampionsRoute
  '/cup': typeof CupRoute
  '/fixtures': typeof FixturesRoute
  '/injuries': typeof InjuriesRoute
  '/lineup': typeof LineupRoute
  '/match': typeof MatchRoute
  '/scorers': typeof ScorersRoute
  '/season': typeof SeasonRoute
  '/squad': typeof SquadRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRoute
  '/transfers': typeof TransfersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assists': typeof AssistsRoute
  '/calendar': typeof CalendarRoute
  '/champions': typeof ChampionsRoute
  '/cup': typeof CupRoute
  '/fixtures': typeof FixturesRoute
  '/injuries': typeof InjuriesRoute
  '/lineup': typeof LineupRoute
  '/match': typeof MatchRoute
  '/scorers': typeof ScorersRoute
  '/season': typeof SeasonRoute
  '/squad': typeof SquadRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRoute
  '/transfers': typeof TransfersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assists': typeof AssistsRoute
  '/calendar': typeof CalendarRoute
  '/champions': typeof ChampionsRoute
  '/cup': typeof CupRoute
  '/fixtures': typeof FixturesRoute
  '/injuries': typeof InjuriesRoute
  '/lineup': typeof LineupRoute
  '/match': typeof MatchRoute
  '/scorers': typeof ScorersRoute
  '/season': typeof SeasonRoute
  '/squad': typeof SquadRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRoute
  '/transfers': typeof TransfersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assists'
    | '/calendar'
    | '/champions'
    | '/cup'
    | '/fixtures'
    | '/injuries'
    | '/lineup'
    | '/match'
    | '/scorers'
    | '/season'
    | '/squad'
    | '/standings'
    | '/teams'
    | '/transfers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assists'
    | '/calendar'
    | '/champions'
    | '/cup'
    | '/fixtures'
    | '/injuries'
    | '/lineup'
    | '/match'
    | '/scorers'
    | '/season'
    | '/squad'
    | '/standings'
    | '/teams'
    | '/transfers'
  id:
    | '__root__'
    | '/'
    | '/assists'
    | '/calendar'
    | '/champions'
    | '/cup'
    | '/fixtures'
    | '/injuries'
    | '/lineup'
    | '/match'
    | '/scorers'
    | '/season'
    | '/squad'
    | '/standings'
    | '/teams'
    | '/transfers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistsRoute: typeof AssistsRoute
  CalendarRoute: typeof CalendarRoute
  ChampionsRoute: typeof ChampionsRoute
  CupRoute: typeof CupRoute
  FixturesRoute: typeof FixturesRoute
  InjuriesRoute: typeof InjuriesRoute
  LineupRoute: typeof LineupRoute
  MatchRoute: typeof MatchRoute
  ScorersRoute: typeof ScorersRoute
  SeasonRoute: typeof SeasonRoute
  SquadRoute: typeof SquadRoute
  StandingsRoute: typeof StandingsRoute
  TeamsRoute: typeof TeamsRoute
  TransfersRoute: typeof TransfersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squad': {
      id: '/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof SquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season': {
      id: '/season'
      path: '/season'
      fullPath: '/season'
      preLoaderRoute: typeof SeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorers': {
      id: '/scorers'
      path: '/scorers'
      fullPath: '/scorers'
      preLoaderRoute: typeof ScorersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineup': {
      id: '/lineup'
      path: '/lineup'
      fullPath: '/lineup'
      preLoaderRoute: typeof LineupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/injuries': {
      id: '/injuries'
      path: '/injuries'
      fullPath: '/injuries'
      preLoaderRoute: typeof InjuriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cup': {
      id: '/cup'
      path: '/cup'
      fullPath: '/cup'
      preLoaderRoute: typeof CupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions': {
      id: '/champions'
      path: '/champions'
      fullPath: '/champions'
      preLoaderRoute: typeof ChampionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assists': {
      id: '/assists'
      path: '/assists'
      fullPath: '/assists'
      preLoaderRoute: typeof AssistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistsRoute: AssistsRoute,
  CalendarRoute: CalendarRoute,
  ChampionsRoute: ChampionsRoute,
  CupRoute: CupRoute,
  FixturesRoute: FixturesRoute,
  InjuriesRoute: InjuriesRoute,
  LineupRoute: LineupRoute,
  MatchRoute: MatchRoute,
  ScorersRoute: ScorersRoute,
  SeasonRoute: SeasonRoute,
  SquadRoute: SquadRoute,
  StandingsRoute: StandingsRoute,
  TeamsRoute: TeamsRoute,
  TransfersRoute: TransfersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
